clusterID: ""
organization: ""
managementCluster: ""

apps:
  dex-app:
    appName: dex-app
    chartName: dex-app
    catalog: giantswarm
    enabled: true
    namespace: giantswarm
    # used by renovate
    # repo: giantswarm/dex-app
    version: 1.41.0
    clusterValues:
      configMap: true
      secret: true
    userConfig:
      configMap:
        values: |
          ingress:
            externalDNS: true
            ingressClassName: auth
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs: []

  athena:
    appName: athena
    chartName: athena
    catalog: giantswarm
    enabled: true
    clusterValues:
      configMap: true
      secret: true
    namespace: giantswarm
    # used by renovate
    # repo: giantswarm/athena
    version: 1.12.0
    userConfig:
      configMap:
        values: |
          ingress:
            externalDNS: true
            ingressClassName: auth
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: configMap
        name: "{{ $.Values.clusterID }}-default-auth-config"
        namespace: "{{ $.Release.Namespace }}"

  rbac-bootstrap:
    appName: default-rbac-bootstrap
    chartName: rbac-bootstrap
    catalog: giantswarm
    enabled: true
    clusterValues:
      configMap: false
      secret: false
    namespace: giantswarm
    # used by renovate
    # repo: giantswarm/rbac-bootstrap-app
    version: 0.2.1
    userConfig: {}
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: configMap
        name: "{{ $.Values.clusterID }}-default-auth-config"
        namespace: "{{ $.Release.Namespace }}"

  ingress-nginx:
    appName: default-ingress-nginx
    chartName: ingress-nginx
    catalog: giantswarm
    enabled: true
    clusterValues:
      configMap: true
      secret: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/ingress-nginx-app
    version: 3.2.1
    userConfig:
      configMap:
        values: |
          controller:
            ingressClassResource:
              name: auth
              controllerValue: k8s.io/ingress-nginx-auth
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs: []
