clusterID: ""
organization: ""
managementCluster: ""

apps:
  dex-app:
    appName: dex-app
    chartName: dex-app
    catalog: giantswarm-test
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/dex-app
    version: 1.36.0-442e1c2857d914b783753185715c0cce325b6e10
    clusterValues:
      configMap: true
      secret: true
    userConfig:
      configMap:
        values: |
          ingress:
            externalDNS: true
            ingressClassName: auth
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs: []

  athena:
    appName: athena
    chartName: athena
    catalog: giantswarm-test
    enabled: true
    clusterValues:
      configMap: true
      secret: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/athena
    version: 1.10.2-88bcbf378056ca6538c584a8451c155b18af041d
    userConfig:
      configMap:
        values: |
          ingress:
            externalDNS: true
            ingressClassName: auth
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: configMap
        name: "{{ $.Values.clusterID }}-default-auth-config"
        namespace: "{{ $.Release.Namespace }}"

  rbac-bootstrap:
    appName: default-rbac-bootstrap
    chartName: rbac-bootstrap
    catalog: giantswarm
    enabled: true
    clusterValues:
      configMap: false
      secret: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/rbac-bootstrap-app
    version: 0.2.1
    userConfig: {}
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: configMap
        name: "{{ $.Values.clusterID }}-default-auth-config"
        namespace: "{{ $.Release.Namespace }}"
