version: 2.1
orbs:
  architect: giantswarm/architect@6.4.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        name: app-catalog
        context: architect
        executor: app-build-suite
        app_catalog: giantswarm-playground-catalog
        app_catalog_test: giantswarm-playground-test-catalog
        chart: auth-bundle
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        name: app-catalog
        context: architect
        executor: app-build-suite
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: auth-bundle
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
